### ISSUE TITLE
Azure reference clarification

### ISSUE THREAD

**Issue by acastrobasurto** [humanitec-architecture/reference-architecture-azure#18]
Hi Humanitec team. 

First thank you so much for providing this arch reference for us to use. Me and another Engineer are trying to deploy the reference arch into our Azure account to understand more about the interactions between Azure and Humanitec; While doing so we ran into an issue with the following resource: humanitec_resource_account" "cluster_account", 

```
Error: Humanitec API error
│ 
│   with module.base.humanitec_resource_account.cluster_account,
│   on modules/base/humanitec.tf line 10, in resource "humanitec_resource_account" "cluster_account":
│   10: resource "humanitec_resource_account" "cluster_account" {
│ 
│ Unable to create resource account, unexpected status code: 400, body:
│ {"error":"HTTP-400","message":"Resource Account credentials do not match type
│ requirements: at /required: missing properties: 'appId', 'password', 'tenant'"}
```

We looked at the official documentation and we found out there are two types that might be applicable here. 

Here is one snippet for type `azure-identity`

```
resource "humanitec_resource_account" "azure-identity" {
  id   = var.cloud_account_id
  name = var.cloud_account_name
  type = "azure-identity"
  credentials = jsonencode({
    azure_identity_tenant_id = var.azure_identity_tenant_id
    azure_identity_client_id = var.azure_identity_client_id
  })
}
```

And type `azure`

```
resource "humanitec_resource_account" "azure" {
  id   = var.cloud_account_id
  name = var.cloud_account_name
  type = "azure"
  credentials = jsonencode({
    "appId"    = var.azure_client_id
    "password" = var.azure_client_secret
    "tenant"   = var.azure_tenant_id
  })
}
```

My gut feeling says use`azure-identity` since it looks similar of what is currently in the [humanitec.tf](https://github.com/humanitec-architecture/reference-architecture-azure/blob/main/modules/base/humanitec.tf#L8) file.

Thanks for the clarification and if this works to update the ref-arch source code, I figured just open an issue to make more people aware.

**Comment by joahuber** [comment]
I ran into the same issue.

**Comment by astromechza** [comment]
@acastrobasurto / @joahuber Well spotted, that's exactly right, the account type there should be `azure-identity`. PR coming now.
